using System.Collections.Generic;

namespace StackSizes
{
    public class StackSizesItemList
    {
        public List<string> ItemList = new List<string>()
        {
            "556 Ammo",
            "9mm Ammo",
            "Handmade Shell",
            "Shotgun Shells",
            "Arrow",
            "Anti-Radiation Pills",
            "Can of Beans",
            "Can of Tuna",
            "Chocolate Bar",
            "Cooked Chicken Breast",
            "Granola Bar",
            "Raw Chicken Breast",
            "Small Rations",
            "Small Water Bottle",
            "Bed",
            "Metal Ceiling",
            "Metal Doorway",
            "Metal Foundation",
            "Metal Pillar",
            "Metal Ramp",
            "Metal Stairs",
            "Metal Wall",
            "Metal Window",
            "Wood Ceiling",
            "Wood Doorway",
            "Wood Foundation",
            "Wood Pillar",
            "Wood Ramp",
            "Wood Stairs",
            "Wood Wall",
            "Wood Window",
            "Camp Fire",
            "Explosive Charge",
            "Furnace",
            "Large Spike Wall",
            "Large Wood Storage",
            "Metal Door",
            "Metal Window Bars",
            "Repair Bench",
            "Sleeping Bag",
            "Small Stash",
            "Spike Wall",
            "Wood Barricade",
            "Wood Gate",
            "Wood Gateway",
            "Wood Shelter",
            "Wood Storage Box",
            "Wooden Door",
            "Workbench",
            "Explosives",
            "Gunpowder",
            "Bandage",
            "Large Medkit",
            "Small Medkit",
            "Flare",
            "Animal Fat",
            "Blood",
            "Charcoal",
            "Cloth",
            "Leather",
            "Low Grade Fuel",
            "Low Quality Metal",
            "Metal Fragments",
            "Metal Ore",
            "Paper",
            "Stones",
            "Sulfur",
            "Sulfur Ore",
            "Wood",
            "Wood Planks",
            "Blood Draw Kit",
            "Handmade Lockpick",
            "Recycle Kit 1",
            "Research Kit 1",
            "F1 Grenade",
            "Supply Signal"
        };
    }
}
